services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"

    networks:
      - pokus_net

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - pokus_net

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - pokus_net

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - pokus_net

  # rabbitmq:
  #   image: rabbitmq:management
  #   restart: unless-stopped
  #   ports:
  #     - "5672:5672" # AMQP port
  #     - "15672:15672" # Management UI
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   volumes:
  #     - rabbitmq-data:/var/lib/rabbitmq
  #   networks:
  #     - pokus_net

volumes:
  mongodb-data:
  # rabbitmq-data:

networks:
  pokus_net:
    driver: bridge
